### ISSUE TITLE
Can't run my own instance following README.md

### ISSUE THREAD

**Issue by agustif** [thoughtbot/constable#423]
Maybe the README is not updated for people outside the thoughtbot team to contribute without being able to work on the heroku project, I tried by myself to change .env and such to match with no much success, I saw you had a different dyno set-up for heroku reviews but didn't see where to get the code to run that.

Anyways, should I wait I little bit? I just wanted to try and implement Page Specific Titles as requested on #416

**Comment by paulcsmith** [comment]
Hi @agustif, yes the README is mostly written for people with access to our thoughtbot Heroku accounts. I'll have to make sure to update it to make it easier for others. 

You should be able to get Constable set up without access to our Heroku review apps though. You will have to get a client id and client secret from Google in order to get OAuth working. Alternatively you could add tests and test that page titles are added correctly. Then when you submit the PR we can check it out and make sure it works

**Comment by agustif** [comment]
I tried to solve the google thing by myself, I do have the Oauth client and secret, where would I put them?

**Comment by BlakeWilliams** [comment]
You would put it in `.env` as `CLIENT_ID` and `CLIENT_SECRET`.

**Comment by BlakeWilliams** [comment]
Closing this since #424 may resolve the issue. Feel free to re-open it if there's any more confusion.
