### ISSUE TITLE
Rename “Interests” to “Topics”

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#702]
Extracted from conversation in https://github.com/thoughtbot/constable/issues/691 …

As @WilHall pointed out:

> I think that naming [(topics)] clarifies what we use them for (for example "boston" is exactly an interest)

Between three of our websites, we use three different labels to group content:

- Blog: [Topics](https://thoughtbot.com/blog/tags)
- Constable: [Interests](https://constable.io/interests)
- Ask: [Tags](https://ask.thoughtbot.com/tags)

The grouping of content on these sites is structurally the same (and in fact, we use the same grouping terms quite often, e.g. `accessibility`, `formkeep`, `marketing`, `raleigh`, etc.), so that mental overhead of using unique labels is not needed. 

Can we use one shared language? I’m personally leaning towards “Topics.”

**Comment by WilHall** [comment]
I am also leaning towards "Topics" - curious what others think @germsvel @stratigos @mike-burns

**Comment by stratigos** [comment]
I dont have much of an opinion. In my head theyre all "tags". I also dont have a problem with regarding `boston` as an "interest". 

I also dont mind if `Interest` is changed to `Topic` :slightly_smiling_face: I do think changing a class/module name is a cost, and would think its best to have a strong collective opinion for doing so.

**Comment by WilHall** [comment]
>  I do think changing a class/module name is a cost, and would think its best to have a strong collective opinion for doing so

Definitely - this wouldn't be a small renaming operation...

**Comment by germsvel** [comment]
I like `Topics` better than `Tags` simply because I think `Topics` keep more of the connotation that you are subscribing to receive updates on a certain area (I'm guessing that's why we had "interests" first). On the other hand, though `Tags` function similarly in that you can choose more than one, I think of them more as a filtering mechanism when you're searching through a list. I should say, I don't mind keeping "interests" either, but I see why we might want to change them.
