### ISSUE TITLE
Posting an announcement to/with zero Interests

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#740]
It is currently possible to post an announcement to/with zero Interests. [A recently posted announcement](https://constable.io/announcements/2218-new-advisor-skill-added-to-hub) made me aware of that.

At least in the case of this particular announcement, it being “tagged” with no Interest means the information is likely to have not reached people whom might find it valuable to have been notified of its existance.

I spoke with @knittingarch, who posted the announcement, to learn more about why no Interests were added, to which they very kindly responded with:

> I didn't realize I needed to add one.  I assumed since this applied to everyone, I shouldn't add anything.

This feels like a breakdown in the design and begs the question: How might we make it more clear how Interests work and/or when an announcement will (potentially) not reach anyone?

---

Interestingly, we already have a feature that will tell you how many people subscribe to the Interests you’ve selected:

![Screen Shot 2019-09-19 at 14 43 13](https://user-images.githubusercontent.com/903327/65272031-52ee5980-daec-11e9-931b-88688295b313.png)

…but that’s only if you add at least one Interest…

**Comment by stratigos** [comment]
What do you think about defaulting that text to be:

`0 people are subscribed to these interests`

...until that number can be calculated, i.e., one or more Interests are associated.

**Comment by WilHall** [comment]
I think both #702 and #707 are very relevant here because they may influence the way people think about "interests" and the "everyone interest".

I feel like there are three general stances we could take on this situation:
1. An announcement can be created with zero or many interests (what we do today) implying that there is a valid use case for a user to create an announcement without any interests (what is that case?) and make it obvious to the user
2. An announcement can be created with one or more interests. We would disallow via form validation and the model the creation of an announcement with no interests. (and also would probably want to add clarifications like @stratigos suggested do this is obvious to the user)
3. Building off @knittingarch's understanding, we could make it so that an announcement with "no interests" implicitly has an interest of "everyone"

I think `2` is our best option, because the experience could be something like the following:
 - User visits the Announcement form
 - The interests field is empty, and displays an empty state message similar to @stratigos's suggestion
 - If the user tries to submit the form with no interests, we can provide a validation error
 - We can enforce that restriction at the model level to make the intention clear

An additional idea that came to mind was pre-filling the interests field with the "everyone" interest. Doing so would mean that the default behavior if you don't modify the field is clear. We could still enforce at least one interest through validation, but this accelerates the process of writing an announcement to everyone when the user doesn't have a particular audience in mind.

**Comment by stratigos** [comment]
> 3. Building off @knittingarch's understanding, we could make it so that an announcement with "no interests" implicitly has an interest of "everyone"

This sounds like the simplest solution with the least amount of work.

At first I was thinking this might create one of those, "oh shoot, I diddnt want to cc the whole company!" situations. I think for this application, that would be quite rare. I also think someone using the application that wants a specific Interest would note that `everyone` is already added, and remove it if need be. These are assumptions though, so while I think the risk is minimal, its worth noting that people will need to be aware of something they werent previously aware of.

> 2. An announcement can be created with one or more interests. We would disallow via form validation and the model the creation of an announcement with no interests. (and also would probably want to add clarifications like @stratigos suggested so that this is obvious to the user)

While it requires more work, I think this is the best solution, assuming there is a decision that there is no valid use case for having no Interest. 

> 1. An announcement can be created with zero or many interests (what we do today) implying that there is a valid use case for a user to create an announcement without any interests (what is that case?) and make it obvious to the user

I also feel fine about this, but feel we will also want to denote `0 people subscribed...`

**Comment by tysongach** [comment]
I also agree that the second option above…

> An announcement can be created with one or more interests. We would disallow via form validation and the model the creation of an announcement with no interests.

…is the best solution and would encourage intentional, accurate behavior.
