### ISSUE TITLE
Announcements page is very slow to load

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/constable#887]
I haven't measured this very precisely, but I'm noticing that when I visit `/announcements` the page currently takes well over 30 seconds to load.

**Comment by germsvel** [comment]
I did a little bit of digging into this. I believe the issue is coming from fetching the profile urls and image urls from hub. We used to use gravatar, and that just required generating a url hash for each avatar. But now that we use hub, we try to memoize the urls. But when the cache isn't warm, this can take a really long time. I'll try to get to this later this week, but if I can't, I hope this note helps someone else fix this.

**Comment by germsvel** [comment]
I'm working on a solution for now where we no longer memorize those values, but instead, we fetch them from hub every so often and store them in the database. That way, when we load a page, we already have the values. 

This is still a little weird because one of the best times to do that is when the user is created. But the values for creation are (I think) coming from hub. So we have something like this going on, 

```
hub | -- create a user (email, name)       --> | constable 
hub | <-- what is the user's profile info? --  | constable
hub | -- profile_url and profile_image_url --> | constable
```

So ultimately, the best solution would be for hub to just provide this information to us whenever a user is created (currently hub only sends the email and name). Until then, however, I think fetching the info whenever we want/need it would work fine.
